### ISSUE TITLE
Improve packaging & publish to Packagist

### ISSUE THREAD

**Issue by virtualtam** [shaarli/netscape-bookmark-parser#15]
TODO:
- [x] add Composer metadata
  - authors
  - supported PHP versions
  - version
- [x] ~~https://github.com/kafene/netscape-bookmark-parser/issues/6 - tag and release a new version under `kafene/netscape-bookmark-parser`~~
- [x] create a Packagist account for Shaarli community packages
- [x] #26 - update Composer metadata to use the `shaarli/netscape-bookmark-parser` namespace
- [x] tag and release a new version
- [x] create the actual package entry
- [x] generate the package archive
- [x] setup a GitHub -> Packagist webhook

See:
- https://getcomposer.org/doc/04-schema.md
- https://packagist.org/

**Comment by virtualtam** [comment]
As there's no feedback on the upstream issue to create new tagged releases, I'm considering creating a `shaarli/netscape-bookmark-parser` repository on Packagist.

Here's what we currently have:
- NetscapeBookmarkParser:
  - `master` branch tracking the upstream `master`
  - `shaarli-devel` branch acting as our `master`
  - `shaarli-stable` branch to enable using a Composer SCM backend for Shaarli (Composer is a bit too restrictive when it comes to tag names to pin dependencies)
  - tags use the `shaarli-vX.Y.Z` format, which is not considered valid by Composer
- Shaarli:
  - hack using an SCM repository backend to override dependency resolving so it points to our fork
  - aformentioned `shaarli-stable` branch hack
  - requires `git` to be installed to grab this particular dependency

Proposition:
- create a `shaarli/netscape-bookmark-parser` Packagist repository
- cleanup this fork's branches:
  - work on `master`
  - (optional) provide a `stable` branch - not sure this is extra useful, there shouldn't be a lot of modifications
- tag releases as `vX.Y.Z`
- Shaarli: cleanup Composer config to point to our Packagist repository & resolve it using HTTPS

**Comment by ArthurHoaro** [comment]
I agree with your proposition.

> (optional) provide a stable branch - not sure this is extra useful, there shouldn't be a lot of modifications

That's not necessary. The stable branch in Shaarli will point to a specific tag.

**Comment by virtualtam** [comment]
I've made the following changes to this repository:
- switch to a single `master` branch
  - delete the `shaarli-devel` and `shaarli-stable` branches
- tags:
  - `v1.0.1` - current `master`
  - `v1.0.0` - same as the former `shaarli-v0.8.0`
  - delete `shaarli-v0.8.0` as it's referenced nowhere and this code is not used in production yet

The Packagist repository is:
- up and running at https://packagist.org/packages/shaarli/netscape-bookmark-parser
- referenced in Shaarli - https://github.com/shaarli/Shaarli/pull/632

https://github.com/shaarli/Shaarli/pull/612 rebased accordingly
