### ISSUE TITLE
First link not imported with the old export format

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/netscape-bookmark-parser#24]
I exported my database from Shaarli v0.6.4, so before you refactored the bookmark exporting.

In this version, the first link is on the same line as the title:

``` html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
<!-- Shaarli all bookmarks export on 2016/08/08 10:04:26 -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1><DT><A HREF="https://gist.github.com/rodrigomuniz/8408734" ADD_DATE="1470640652" PRIVATE="1" TAGS="css">A Pen by Rodrigo Muniz.</A>
<DD>simple on/off button 
<DT><A HREF="https://www.addedbytes.com/articles/for-beginners/url-rewriting-for-beginners/" ADD_DATE="1469950052" PRIVATE="0" TAGS="apache">URL Rewriting for Beginners - Web Development in Brighton - Added Bytes</A>
```

When I try to import back this file (using your PR with this parser), the first link is not imported. We would expect it to be able to import files from Shaarli older version.

**Comment by virtualtam** [comment]
Looks like the sanitizing step is a bit aggressive ;-)

https://github.com/shaarli/netscape-bookmark-parser/blob/master/NetscapeBookmarkParser.php#L229
