### ISSUE TITLE
Tests: add coverage for Shaarli parsing

### ISSUE THREAD

**Issue by virtualtam** [shaarli/netscape-bookmark-parser#5]

**Comment by virtualtam** [comment]
Currently working on this, for now I have a nice set of links for a vanilla (no plugin enabled) Shaarli setup.

@ArthurHoaro would you have example dumps or ideas representative of the usage of text formatting plugins? (e.g. Markdown)

**Comment by ArthurHoaro** [comment]
No sorry, I've accidentally lost my local datastore. But I usually use stuff like this https://stackedit.io/editor, add a bit of HTML, and that's a good base.

**Comment by virtualtam** [comment]
No worries; I'll start by covering Markdown formatting that can be useful for Shaarli notes: font weight, lists, quotes, code blocks, etc.

**Comment by virtualtam** [comment]
Actually, the bookmark file generated by Shaarli is not valid, even according to the very loose Netscape format specification. I'll submit a PR to fix this and use a template as well.

[EDIT] https://github.com/shaarli/Shaarli/pull/538 in review ;-)

**Comment by nodiscc** [comment]
While working on this, could you have a look at https://github.com/shaarli/Shaarli/issues/102 ? I did investigate a bit but didn't find why the import from Shaarli bookmarks failed mid-way. I suspect invalid formatting somewhere...

**Comment by virtualtam** [comment]
- Shaarli-specific anwser @ https://github.com/shaarli/Shaarli/issues/102#issuecomment-209115228
- feel free to open issues here with browser dumps (Firefox, Iceweasel, Chrom-e/-ium, etc.) attached, whether they lead to faulty imports or not (the more test data, the better ^^)

**Comment by nodiscc** [comment]
> browser dumps attached,

I will provide this, please check my question at https://github.com/shaarli/Shaarli/issues/102#issuecomment-209478895.

**Comment by nodiscc** [comment]
This entry

```
<DT><A HREF="?r5AciA" ADD_DATE="1457655999" PRIVATE="0" TAGS="quotes,wtf,linux">UNIX</A>
<DD>&gt; I’ve used a chainsaw, and you’re simultaneously amazed at (1) how easily it slices through a tree, and (2) that you’re dumb enough to use this thing three feet away from your vital organs. This is Unix.
```

causes Firefox import to stop.

**Comment by virtualtam** [comment]
Thanks!
I think it's related to @ArthurHoaro 's comment that bookmark dumps featuring Shaarli notes fail at being imported. I think a clean way to fix this would be to add a _Prepend server URL_ checkbox to Shaarli exports so users can choose whether to prepend note permalinks with their Shaarli instance's URL.
