### ISSUE TITLE
"ksort() expects parameter 1 to be array, null given" when trying to parse an empty bookmarks file

### ISSUE THREAD

**Issue by Kovah** [shaarli/netscape-bookmark-parser#50]
When trying to import an empty bookmarks file, the process fails with a PHP error:

```
ksort() expects parameter 1 to be array, null given at /app/vendor/shaarli/netscape-bookmark-parser/NetscapeBookmarkParser.php:203
```

Instead of this behavior, the parser should either throw a custom exception, or simply return an empty array. The former would be preferable to be as explicit as possible.

**Comment by ArthurHoaro** [comment]
Thanks for the report.
