### ISSUE TITLE
Why is there no rule to match icon

### ISSUE THREAD

**Issue by WeakChickenPeng** [shaarli/netscape-bookmark-parser#73]
use composer require shaarli/netscape-bookmark-parser
no rule to match 'icon'

download zip
There are matching rules about ‘icon‘’

**Comment by TangoMan75** [comment]
Hi WeakChickenPeng, what do you mean "no rule" ?

**Comment by WeakChickenPeng** [comment]
I mean to say ，no code for match “icon”------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Matthias&amp;nbsp;Morin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月10日(星期三) 晚上10:08
收件人:&nbsp;&quot;shaarli/netscape-bookmark-parser&quot;<netscape-bookmark-parser@noreply.github.com&gt;;
抄送:&nbsp;&quot;WeakChickenPeng&quot;<1024668480@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shaarli/netscape-bookmark-parser] Why is there no rule to match icon (#73)

**Comment by ArthurHoaro** [comment]
Hi, icon parsing has been added by @TangoMan75 in #70. I'll push a release with this change before merging #72 after double checking that there is no BC break.

**Comment by ArthurHoaro** [comment]
https://github.com/shaarli/netscape-bookmark-parser/releases/tag/v3.2.0
