### ISSUE TITLE
Using with Laravel

### ISSUE THREAD

**Issue by nickworks** [shaarli/netscape-bookmark-parser#81]
Hello! I'm trying to use this in one of my Service classes in a Laravel project, but I can't seem to get it to work.

I've run
```
composer require shaarli/netscape-bookmark-parser
```

I've added to `composer.json`:
```
"autoload": {
    "psr-4": {
        "App\\": "app/",
        "Database\\Factories\\": "database/factories/",
        "Database\\Seeders\\": "database/seeders/",
        "Shaarli\\NetscapeBookmarkParser\\":"vendor/shaarli/netscape-bookmark-parser/"
    }
},
```

I've run
```
composer dump-autoload
```

The following line of code yields the proceeding `Symfony \ Component \ ErrorHandler \ Error \ FatalError` error:
```
$parser = new \Shaarli\NetscapeBookmarkParser\NetscapeBookmarkParser();
```
```
Cannot declare class NetscapeBookmarkParser, because the name is already in use
```

I've tried some other approaches with no success. If I remove (or change) the autoload line from composer, then the error is that the class NetscapeBookmarkParser couldn't be found.

Anyone know what I'm doing wrong here? Thanks!

**Comment by WileESpaghetti** [comment]
I'm using with Laravel and I don't have it in my psr-4 section. I only had to require.

composer.json looks like this
```
"require": {
        "shaarli/netscape-bookmark-parser": "^4.0"
    },
```

The places that I am using that class it's basically like this
```php
use Shaarli\NetscapeBookmarkParser\NetscapeBookmarkParser;

class Example {
  function do() {
    $parser1 = new NetscapeBookmarkParser();                                 // manually create a parser
    $parser2 = $this->app->make(NetscapeBookmarkParser::class);  // ask Laravel service container for a parser
  }

  function alsoDo(NetscapeBookmarkParser $parser3) {
    // $parser3 is populated by the service container. Can also do this in the constructor if you need it there.
  }
}
```

If none of those work after doing a `dump-autoload` there might be an artisan cache that needs to be clear, or worse case maybe try renaming your vendor folder and doing a `composer install` again. Oh, also double check to make sure the class is actually on the server. There have been times I've almost pulled my hair out troubleshooting why a change isn't appearing only to realize the file never actually got uploaded to the server. Same with the `dump-autoload`. Those changes might not get uploaded too.

**Comment by nickworks** [comment]
It looks like the problem was that composer was requiring "^1.1" -- updating it to "^4.0" and removing the ps-4 autoloader fixed the issue. Thank you!!
